{
 "title": "Energy_monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Stand3_Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"reading_time\",'1s'),\r\n  avg(current_a) as current_a\r\nFROM sensor_data3 \r\nWHERE $__timeFilter(\"reading_time\")\r\nGROUP BY time\r\nORDER BY time"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"reading_time\",'1s'),\r\n  avg(current_b) as current_b\r\nFROM sensor_data3 \r\nWHERE $__timeFilter(\"reading_time\")\r\nGROUP BY time\r\nORDER BY time"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"reading_time\",'1s'),\r\n  avg(current_c) as current_c\r\nFROM sensor_data3 \r\nWHERE $__timeFilter(\"reading_time\")\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Stand2_Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"reading_time\",'1s'),\r\n  avg(voltage_a) as current_a\r\nFROM sensor_data2 \r\nWHERE $__timeFilter(\"reading_time\")\r\nGROUP BY time\r\nORDER BY time"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"reading_time\",'1s'),\r\n  avg(voltage_b) as current_b\r\nFROM sensor_data2 \r\nWHERE $__timeFilter(\"reading_time\")\r\nGROUP BY time\r\nORDER BY time"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"reading_time\",'1s'),\r\n  avg(voltage_c) as current_c\r\nFROM sensor_data2 \r\nWHERE $__timeFilter(\"reading_time\")\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Stand3_Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"reading_time\",'1s'),\r\n  avg(voltage_a) as voltage_a\r\nFROM sensor_data3 \r\nWHERE $__timeFilter(\"reading_time\")\r\nGROUP BY time\r\nORDER BY time"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"reading_time\",'1s'),\r\n  avg(voltage_b) as voltage_b\r\nFROM sensor_data3 \r\nWHERE $__timeFilter(\"reading_time\")\r\nGROUP BY time\r\nORDER BY time"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"reading_time\",'1s'),\r\n  avg(voltage_c) as voltage_c\r\nFROM sensor_data3 \r\nWHERE $__timeFilter(\"reading_time\")\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Stand1_Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"reading_time\",'1s'),\r\n  avg(voltage) as current\r\nFROM sensor_data1 \r\nWHERE $__timeFilter(\"reading_time\")\r\nGROUP BY time\r\nORDER BY time"
    },
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    },
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Work status",
   "type": "timeseries",
   "description": "0 - off,\n1 - pass,\n2 - on",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"push_time\",'1h'),\r\n  avg(work_status) as work_status\r\nFROM regs3\r\nWHERE $__timeFilter(\"push_time\")\r\nGROUP BY time\r\nORDER BY time"
    },
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  }
 ]
}